name: Typeset document
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  typeset-document:
    name: Typeset document
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Lilypond
        run: |
          set -e
          sudo apt-get -qy update
          sudo apt-get -qy install --no-install-recommends lilypond
      - name: Typeset score
        run: lilypond document.ly
