name: Typeset document
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  typeset-document:
    name: Typeset document
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
      options: --user root --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Lilypond
        run: |
          set -e
          apt -y update
          apt -y install curl bzip2
          curl https://lilypond.org/download/binaries/linux-64/`curl https://lilypond.org/download/binaries/linux-64/ | grep -o 'lilypond[^>]*sh' | tail -1` > lilypond.sh
          sh ./lilypond.sh --batch
      - name: Typeset score
        run: |
          lilypond document.ly
      - name: Typeset lyluatex test
        run: |
          lualatex -shell-escape document.tex
