name: Typeset document
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  typeset-document:
    name: Typeset document
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Lilypond
        run: |
          set -e
          apt-get -qy update
          apt-get -qy install --no-install-recommends lilypond
      - name: Typeset score with Lilypond
        run: lilypond document.ly
      - name: Typeset score with LyLuatex
        run: lualatex -shell-escape document.tex
