name: Typeset document
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  typeset-document:
    name: Typeset document
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Lilypond
        run: |
          set -e
          wget https://lilypond.org/download/binaries/linux-64/lilypond-2.22.2-1.linux-64.sh
          sh ./lilypond-2.22.2-1.linux-64.sh --batch
      - name: Typeset score
        run: lilypond document.ly
